{
 "title": "Container Monitoring",
 "description": "Docker container monitoring powered by cAdvisor",
 "tags": [
  "monitoring",
  "container",
  "cadvisor",
  "Docker"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ContainerName",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{name=~\".+\"}, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime Containers",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=~\"$ContainerName\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\".+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Total Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1m]))",
     "legendFormat": "Input"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[1m]))",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=~\".+\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=~\".+\"}[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "CPU Total Usage",
   "type": "timeseries",
   "description": "CPU usage per container",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\"$ContainerName\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"$ContainerName\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "description": "Network received and transmitted bytes per container",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=~\"$ContainerName\"}[$__rate_interval])",
     "legendFormat": "{{name}} rx"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{name=~\"$ContainerName\"}[$__rate_interval])",
     "legendFormat": "{{name}} tx"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "description": "Disk read and write bytes per container",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{name=~\"$ContainerName\"}[$__rate_interval])",
     "legendFormat": "{{name}} read"
    },
    {
     "expr": "rate(container_fs_writes_bytes_total{name=~\"$ContainerName\"}[$__rate_interval])",
     "legendFormat": "{{name}} write"
    }
   ]
  }
 ]
}